on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          docker build -t my-image .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push my-image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          curl -X POST -u $USERNAME:${{ secrets.API_KEY }} https://api.example.com/deploy
